version: "3.8"

services:
  lti:
    build:
      context: .
      args:
        - "REQUIREMENTS=${REQUIREMENTS}"
    volumes:
      - ./lti:/app
      - type: bind
        source: ./devops/nginx.conf
        target: /app/nginx.conf
      - type: bind
        source: ./devops/uwsgi.ini
        target: /app/uwsgi.ini
      - type: bind
        source: ./generate_keys.py
        target: /app/generate_keys.py
      - type: bind
        source: ./setup.cfg
        target: /app/setup.cfg
      - type: bind
        source: ./pyproject.toml
        target: /app/pyproject.toml
      - type: bind
        source: ./api.json
        target: /app/api.json
    ports:
      - "8000:80"
    env_file:
      - .env
    environment:
      - MODULE_NAME=app
      - FLASK_APP=main.py
      - GOOGLE_APPLICATION_CREDENTIALS=/app/api.json
